### ISSUE TITLE
How to stop camera after scan is completed

### ISSUE THREAD

**Issue by VinayKumarSarda** [bitpay/cordova-plugin-qrscanner#128] opened 2017-11-08 03:30 UTC
Hi ,

The camera is still open after scan is successful. Please let me know how to stop camera after success scan.

**Comment by VinayKumarSarda** [comment] 2017-11-23 04:42
Any help on how to stop camera after scan ???

**Comment by VinayKumarSarda** [comment] 2017-11-27 07:11
HI Please need inputs as my camera is stilla ctive after scanning is done.

**Comment by HeroCC** [comment] 2017-12-25 00:59
Does this work? https://github.com/bitpay/cordova-plugin-qrscanner#destroy

**Comment by VinayKumarSarda** [comment] 2018-01-04 09:23
No @HeroCC

**Comment by VinayKumarSarda** [comment] 2018-01-08 10:29
any inputs @HeroCC @team

**Comment by VinayKumarSarda** [comment] 2018-01-11 10:29
Hi Team,

any inputs on how to close camera ?? in browser once the scan is success still camera is open.

**Comment by VinayKumarSarda** [comment] 2018-01-16 10:10
any update @team @HeroCC

**Comment by DavidRoebl** [comment] 2018-05-14 15:32
I'm having the same issues on Win10/Google Chrome.
After successfully scanning the QR code, I hide the qrScanner (even destroy it for good measure) and then transition to the next screen.
The app does not release the camera though, which is not expecte behaviour and therefore bad UX -- I don't want my users to think that I am spying on them when they use my app :(

```
scan(){
  let scanSub = this.qrScanner.scan().subscribe((text: string) => {
    //here: store scanned text
    this.qrScanner.hide();
    this.qrScanner.destroy();
    scanSub.unsubscribe();
    this.navCtrl.push(NextPage);
  });
}
```

**Comment by bitjson** [comment] 2018-05-17 19:35
I'm not able to reproduce on any local devices, but PRs are certainly welcome. [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) also includes some big improvements which may help.

Closing this for now, but feel free to open a new issue with more specific details.

**Closed by bitjson** 2018-05-17 19:35 UTC

**Comment by SimoneMSR** [comment] 2019-07-10 09:00
This is still an issue with version 3.0.1.
Moreover, this piece of code causes the `scanner.destroy` function to raise an exception that cannot be catched

```
try {
    _this.qrScanner.destroy().then(function (status) {
        _this.hideCamera();
    }).catch(function (error) {
        _this.hideCamera();
    });
}
catch (error) {
    _this.hideCamera();
}
```
if I debug, the `cordova.callbackFromNative` function generates this error
```
{
    code: 6,
    name: "SCAN_CANCELED",
    _message: "Scan was canceled."
}
```

which does not really seem an error.

The errore arises from the `cordova-plugin-qrscanner/src/browser/plugin.min.js`
The `destroy` function cannot procede after the `cancelScan` call because it calls the `cancelNextScan` which in turn throws the code error 6, with the following
```
cancelNextScan = function(sendError){
  window.clearTimeout(nextScan);
  nextScan = null;
  cancelNextScan = null;
  if(sendError){
    error(6); // SCAN_CANCELED
}
```

**Comment by steinsleger** [comment] 2019-09-19 20:15
This is still an issue in current version (browser platform). Camera is not released after invoking .destroy() . Any ideas?

**Comment by katringoogoo** [comment] 2019-10-16 11:47
yup, can confirm ... still an issue :/

**Comment by justgeek** [comment] 2019-12-21 14:44
Have same issue on browser

**Comment by donmb1** [comment] 2020-10-17 13:02
+1

**Comment by dotocan1** [comment] 2021-07-03 19:40
Does anybody know how to route to another page after the scan is complete?

I call the destroy API but that just makes my screen black.

I am doing this in Vue by calling `this.$router.push('/Home')` but it doesn't work.

**Comment by ewojjowe** [comment] 2022-02-28 13:06
+1
