### ISSUE TITLE
Cannot build iOS app - 'openSettingsURLString' has been renamed to 'UIApplicationOpenSettingsURLString'

### ISSUE THREAD

**Issue by adamayoung** [bitpay/cordova-plugin-qrscanner#301] opened 2020-01-30 09:06 UTC
I cannot build an iOS app with this plugin. I get the following errors:

```
                                                   ^
/Users/xxx/MyProject/platforms/ios/MyProject/Plugins/cordova-plugin-qrscanner/QRScanner.swift:471:63: error: 'openSettingsURLString' has been renamed to 'UIApplicationOpenSettingsURLString'
            guard let settingsUrl = URL(string: UIApplication.openSettingsURLString) else {
                                                              ^~~~~~~~~~~~~~~~~~~~~
                                                              UIApplicationOpenSettingsURLString
UIKit.UIApplication:70:22: note: 'openSettingsURLString' was introduced in Swift 4.2
    public class let openSettingsURLString: String
                     ^
/Users/xxx/MyProject/platforms/ios/MyProject/Plugins/cordova-plugin-qrscanner/QRScanner.swift:484:74: error: 'openSettingsURLString' has been renamed to 'UIApplicationOpenSettingsURLString'
                UIApplication.shared.openURL(NSURL(string: UIApplication.openSettingsURLString)! as URL)
                                                                         ^~~~~~~~~~~~~~~~~~~~~
                                                                         UIApplicationOpenSettingsURLString
UIKit.UIApplication:70:22: note: 'openSettingsURLString' was introduced in Swift 4.2
    public class let openSettingsURLString: String
                     ^

** BUILD FAILED **


The following build commands failed:
        CompileSwift normal x86_64 /Users/xxx/MyProject/platforms/ios/MyProject/Plugins/cordova-plugin-qrscanner/QRScanner.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
Command finished with error code 65: xcodebuild -workspace,MyProject.xcworkspace,-scheme, MyProject,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 11 Pro Max,build,CONFIGURATION_BUILD_DIR=/Users/xxx/MyProject/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/xxx/MyProject/platforms/ios/build/sharedpch,EMBEDDED_CONTENT_CONTAINS_SWIFT = YES,ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO,LD_RUNPATH_SEARCH_PATHS = "@executable_path/Frameworks"
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/xxx/MyProject/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[ERROR] An error occurred while running subprocess cordova.
```

**Comment by florian-diatelic** [comment] 2020-01-30 11:37
Yes, it's an known issue. Change `UIApplication.openSettingsURLString` to `UIApplicationOpenSettingsURLString`

**Comment by adamayoung** [comment] 2020-01-30 12:18
Are you planning on fixing this in a new release anytime soon? Making the above change isn't going to help when I do a CI build of the app.

**Comment by jamesopppp** [comment] 2020-02-01 05:39
Same question

**Comment by hanov-paycasso** [comment] 2020-02-03 10:13
> Yes, it's an known issue. Change `UIApplication.openSettingsURLString` to `UIApplicationOpenSettingsURLString`

You can workaround this issue by typing next command in the root of the project: 
`find . -type f -name "*.swift" -print0 | xargs -0 sed -i '' -e 's/UIApplication.openSettingsURLString/UIApplicationOpenSettingsURLString/g'`

**Comment by florian-diatelic** [comment] 2020-02-03 10:27
> Are you planning on fixing this in a new release anytime soon? Making the above change isn't going to help when I do a CI build of the app.

Yes, there is several pull requests to fix it like https://github.com/bitpay/cordova-plugin-qrscanner/pull/251/commits/106abbdf2923f3a65d2ea4a85ab8725077ad6886 . We only wait that it is approved, merged and released by creator. You can fork and doing it

**Comment by danielzen** [comment] 2020-03-28 21:36
I have given up on waiting for this to be fixed. I have created a substitute for the npm package using @markterrill code (Refer #271). If you want to try it run:

``` 
npm uninstall cordova-plugin-qrscanner
npm install git+https://git@github.com/danielzen/cordova-plugin-qrscanner
``` 
Hope it works for you...

**Comment by markterrill** [comment] 2020-03-30 01:13
Cheers @danielzen !

Thanks for the reminder re npm install from git, that'll be very helpful to a lot of folk reading this thread.

Mark

**Comment by danielzen** [comment] 2020-05-18 07:03
Now that I have updated to Swift 5, I understand why @markterrill's code was not accepted. Perhaps it is better to set swift5 in Cordova or Capacitor (as I did)? 

In cordova use: https://www.npmjs.com/package/cordova-plugin-add-swift-support

In capacitor set cordovaSwiftVersion: https://capacitor.ionicframework.com/docs/basics/configuring-your-app/

I'm leaving my Swift 3 version at https://github.com/danielzen/cordova-plugin-qrscanner in the meantime, but I no longer recommend it. Hope this helps.

**Comment by ChiKaLiO** [comment] 2020-12-05 00:38
srsly it has been almost a year now !

**Closed as completed** 2021-05-21 20:57 UTC

**Comment by finorix079** [comment] 2023-04-10 21:39
Is this closed because it is fixed?

**Comment by danielzen** [comment] 2023-04-14 16:47
I recommend looking at:
- https://www.npmjs.com/package/cordova-plugin-qrscanner-11

based on
- https://github.com/v1934/cordova-plugin-qrscanner-11

It has updates that are working for me....

**Comment by mdledoux** [comment] 2023-06-06 16:41
> Is this closed because it is fixed?

@terryjiang2020 - closed because **there is nothing to fix** - it is not a bug - your Cordova iOS settings need to use Swift 5 (at least 4.2, but definitely not 3) and the plugin will work fine.
See @danielzen's [comment above on May 18, 2020](https://github.com/bitpay/cordova-plugin-qrscanner/issues/301#issuecomment-629986900) - also, see [my comment from July 2021](https://github.com/bitpay/cordova-plugin-qrscanner/pull/272#issuecomment-887081111) on this similar issue for more help/details <-- **I believe this holds the answer you are looking for**.

I'm assuming you have an older project, so you probably need an older fix - this was the solution nearly 2 years ago.
But @danielzen's recent [comment on April 14](https://github.com/bitpay/cordova-plugin-qrscanner/issues/301#issuecomment-1508945204) may offer something more current (but I suspect he's using Swift 5 now, so hence how it works for him - just guessing).  I still maintain that a "fix" to the plugin was never needed - just update your project's Swift version (under Cordova settings for iOS), and the newer qrscanner plugin should just work.
